name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"  # Specify the Python version you want to use
        cache: "pip"  # Enable pip caching

    # Step 5: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --only-binary=:all: -r requirements.txt

    # Step 6: Run Pytest to test Redis
    - name: Run Pytest
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        PYTHONPATH: ${{ github.workspace }}
      run: pytest tests/
